version: '3.8'

services:
  mcp-server:
    build: .
    image: python-mcp-server-template:latest
    container_name: mcp-template-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - MCP_SERVER_NAME=docker-template-server
      - MCP_TRANSPORT=http
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8080
      - WORKSPACE_PATH=/workspace
      - LOG_LEVEL=INFO
    volumes:
      - mcp_workspace:/workspace
      - mcp_logs:/tmp/mcp-logs
    healthcheck:
      test: ["CMD", "python", "-c", "from fastmcp import FastMCP; import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - mcp-network

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - mcp-server
  #   networks:
  #     - mcp-network

volumes:
  mcp_workspace:
    driver: local
  mcp_logs:
    driver: local

networks:
  mcp-network:
    driver: bridge
