blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/[your-username]/python-mcp-server-template/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/[your-username]/python-mcp-server-template#readme
    about: Read the project documentation and guides
  - name: 🔒 Security Issues
    url: https://github.com/[your-username]/python-mcp-server-template/security/advisories/new
    about: Report security vulnerabilities privately
