name: 📚 Documentation Issue
description: Report an issue with documentation
title: "[Docs] "
labels: ["documentation", "needs-review"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Please describe the issue you've found.

  - type: dropdown
    id: doc_type
    attributes:
      label: Documentation Type
      description: What type of documentation needs attention?
      options:
        - "README.md"
        - "CONTRIBUTING.md"
        - "API Documentation (docstrings)"
        - "Code Examples"
        - "Configuration Guide"
        - "Troubleshooting"
        - "Installation Instructions"
        - "Docker Documentation"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - "Missing Information"
        - "Incorrect Information"
        - "Outdated Information"
        - "Unclear/Confusing Content"
        - "Formatting Issues"
        - "Broken Links"
        - "Typos/Grammar"
        - "Missing Examples"
        - "Improvement Suggestion"
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue located?
      placeholder: |
        - File: README.md
        - Section: "Quick Start"
        - Line numbers: 45-50
        - URL: (if applicable)
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Content
      description: What does the documentation currently say? (copy/paste relevant section)
      render: markdown
      placeholder: Paste the current documentation content here
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Content
      description: What should the documentation say instead?
      render: markdown
      placeholder: Describe what the documentation should say or provide corrected content
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Why is this change needed? How did you discover this issue?
      placeholder: |
        - How you encountered this issue
        - Impact on users
        - Related documentation that might also need updates
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to help fix this documentation?
      options:
        - label: I'm willing to submit a PR to fix this documentation issue
          required: false
