name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: ["enhancement", "needs-discussion"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out this form to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have reviewed the project roadmap and documentation
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Describe the problem or limitation you're experiencing.
        Example: "As a developer, I find it difficult to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: |
        Describe how you'd like this feature to work.
        Be as detailed as possible about the expected behavior.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions?
      placeholder: |
        Describe any alternative solutions or features you've considered.
        Explain why your proposed solution is better.
    validations:
      required: false

  - type: dropdown
    id: feature_type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - "New MCP Tool"
        - "New Resource Endpoint"
        - "New Prompt Template"
        - "Configuration Enhancement"
        - "Security Improvement"
        - "Performance Optimization"
        - "Developer Experience"
        - "Documentation"
        - "Infrastructure/CI"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Low - Nice to have"
        - "Medium - Would improve workflow significantly"
        - "High - Blocking current use case"
        - "Critical - Required for project viability"
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. Use case: [Describe the scenario]
           Expected outcome: [What should happen]
        
        2. Use case: [Another scenario]
           Expected outcome: [What should happen]
    validations:
      required: true

  - type: textarea
    id: api_design
    attributes:
      label: API/Interface Design (Optional)
      description: If applicable, describe the proposed API or interface
      render: python
      placeholder: |
        @mcp.tool()
        async def my_new_tool(param1: str, param2: int = 10) -> Dict[str, Any]:
            """
            Description of the new tool.
            """
            # Implementation details
            pass
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Considerations
      description: Any thoughts on implementation challenges or requirements?
      placeholder: |
        - Dependencies needed
        - Breaking changes
        - Migration requirements
        - Testing considerations
        - Documentation updates
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would be used
      placeholder: |
        Example usage:
        ```python
        # Show how the feature would be used
        result = await my_new_tool("example", param2=20)
        ```
        
        Expected output:
        ```json
        {
          "result": "example output",
          "status": "✅ Success"
        }
        ```
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to help implement this feature?
      options:
        - label: I'm willing to submit a PR to implement this feature
          required: false
        - label: I can help with testing this feature
          required: false
        - label: I can help with documentation for this feature
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references
      placeholder: |
        - Links to similar implementations
        - Screenshots or mockups
        - Related issues or discussions
        - Research or benchmarks
    validations:
      required: false
