name: ❓ Question/Help
description: Ask a question or request help
title: "[Question] "
labels: ["question", "help-wanted"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question about using the MCP server template? We're here to help!

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before asking
      options:
        - label: I have read the README.md and documentation
          required: true
        - label: I have searched existing issues and discussions
          required: true
        - label: I have tried the troubleshooting steps in the documentation
          required: true

  - type: dropdown
    id: question_type
    attributes:
      label: Question Type
      description: What type of question is this?
      options:
        - "Installation/Setup"
        - "Configuration"
        - "Usage/How-to"
        - "Tool Development"
        - "Docker/Deployment"
        - "Security"
        - "Performance"
        - "Integration"
        - "Best Practices"
        - "Troubleshooting"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please be as specific as possible about what you're trying to achieve
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about your use case or what you're trying to build
      placeholder: |
        - What are you trying to accomplish?
        - What have you tried so far?
        - Any specific requirements or constraints?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: Information about your environment
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, macOS 13.0, Windows 11]
        - Python Version: [e.g., 3.12.0]
        - Docker Version: [e.g., 24.0.0] (if applicable)
        - Template Version: [e.g., 1.0.0]
      value: |
        - OS: 
        - Python Version: 
        - Docker Version: 
        - Template Version: 
    validations:
      required: false

  - type: textarea
    id: code
    attributes:
      label: Relevant Code (if applicable)
      description: Share any relevant code snippets
      render: python
      placeholder: |
        # Share relevant code here
        @mcp.tool()
        async def my_tool():
            pass
    validations:
      required: false

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What solutions have you already attempted?
      placeholder: |
        - Tried solution A: [result]
        - Tried solution B: [result]
        - Searched for: [what you searched]
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other relevant information
      placeholder: |
        - Error messages (if any)
        - Links to related resources
        - Screenshots (if helpful)
    validations:
      required: false
